name: Md to PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/relazione.pdf "Primo Progetto/relazione.md"
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output